### ISSUE TITLE
Using no stopwords for parsing

### ISSUE THREAD

**Issue by mudumat** [miso-belica/jusText#28]
I started to use justext an wonder if it’s possible to use without a language stopp-words. I get an error in the python api but the online demo works with any language. How. I didn’t find anything in the docs. The email adress on that site does'nt work.

**Comment by miso-belica** [comment]
Hi, @mudumat I think you have a similar issue as in https://github.com/miso-belica/jusText/issues/12 in mind :) The author there didn't reply but you can try the code from my last post and let me know if it's OK for you.

Also, you wrote you _get an error in the python api_. May you write what error? With the code you use? Otherwise, I can't help you more.

Have a nice day 😃

**Comment by mudumat** [comment]
Thats a way it seem to work fine so far. Let's unite all stop words of the world 👍 
Thank you for the tip.
